version: "3"

networks:
  web:
    external: true

services:

  strategy-builder:
    build: .
    networks:
      - web
    volumes:
      - "$PWD/index.html:/src/index.html"
    labels:
      - "traefik.http.routers.whoami.rule=PathPrefix(`/bar`)"